# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 363fa3f00952f8729c6611946da1047258669c8efa4fe4db2d3ad95fb11f15b7bed640f7141bef2727301d1f2250be132d00f431a96d786d19e00aaf29052147

test:
  secret_key_base: 9343db9caf2e7ccb50dc9e2a0b907e785622d910422daa835505b02c8ce874840326de18051b755a3544740220055712093f37482d8139327b7e7b6e00e4fe0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
